name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: crpi-sk6clzlmmo6isf61.cn-hangzhou.personal.cr.aliyuncs.com
          username: bencheng520
          password: Chb202503@

      - name: Build and push image to registry
        run: |
          # docker pull
          cat trigger.txt |awk '{print "docker pull "$1} '
          cat trigger.txt |awk '{print "docker pull "$1} '| sh
  
          # docker tag
          cat trigger.txt |awk '{print "docker tag "$1 " " $2} '
          cat trigger.txt |awk '{print "docker tag "$1 " " $2} '| sh
          
          # docker push
          cat trigger.txt |awk '{print "docker push " $2} '
          cat trigger.txt |awk '{print "docker push " $2} '| sh
